name: telecom-churn
namespace: seldon
model:
  image:
    name: 788644545849.dkr.ecr.us-east-2.amazonaws.com/telecom-churn/inference:0.3
    pullPolicy: IfNotPresent
  name: classifier
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
  env:
    LOG_LEVEL: INFO
  #basic log request and responses env vars below just logs raw messages to engine stdout
  #to make searchable log externally - see request logging example
  annotations:
    seldon.io/headless-svc: "false"
    seldon.io/engine-log-requests: "true"
    seldon.io/engine-log-responses: "true"
    seldon.io/engine-log-message-type: "seldon.message.pair"
    seldon.io/engine-log-messages-externally: "true"
replicas: 1

engine:
  resources:
    requests:
      cpu: "0.1"

# Add oauth key and secret if using the default API Oauth Gateway for ingress
oauth:
  key:
  secret:

sdepLabels:
  app: "seldon"

predictorLabels:
  version: "v1"
  fluentd: "true"

autoscaling:
  minReplicas: 1
  maxReplicas: 10
  targetAverageUtilization:
    cpu: 80